### PR TITLE
Add Mimecast Email Cloud Security format

### PR DESCRIPTION
**Pull request by lvoloshyn-sekoia**

### CODE REVIEW

**Review by squioc — CHANGES_REQUESTED** [review]
Thanks for the job.
Some changes to apply.

**Review by squioc — DISMISSED** [review]
LGTM

**Review by Adamowoc — CHANGES_REQUESTED** [review]
Looks good, thanks !

**Comment by Adamowoc** [comment]
Also, I don't think this is Mimecast **advanced** email security, but just Mimecast email security. The logs that are part of the advanced pack (Attachment Protect logs, URL Protect logs, Impersonation Protect logs, AV logs) were not chosen for this integration because they are paying options. @lvoloshyn-sekoia

**Review by Adamowoc — APPROVED** [review]
Thanks for the good work :)

**Pull request merged**
