### PR TITLE
Update Office365 parser.yml

### PR DESCRIPTION
**Pull request by Men-hau**

### CODE REVIEW

**Comment by gcl-sekoia** [comment]
These fields seem to only be used in the SecurityComplianceAlerts record type (40).
Should we move the parsing in a separate stage with a filter on the RecordType?

Microsoft docs:
https://learn.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#security-and-compliance-alerts-schema

**Comment by gcl-sekoia** [comment]
Here's a sample event (all UUIDs have been replaced)
```
{
    "CreationTime": "2023-09-19T06:05:26",
    "Id": "91be566c-0692-4e64-8b23-69d9a4d50390",
    "Operation": "AlertTriggered",
    "OrganizationId": "b3b00feb-0b31-4458-8dc6-612e14e12878",
    "RecordType": 40,
    "ResultStatus": "Succeeded",
    "UserKey": "SecurityComplianceAlerts",
    "UserType": 4,
    "Version": 1,
    "Workload": "SecurityComplianceCenter",
    "ObjectId": "3d903b26-58e4-43bb-b557-1f583fd28a4d",
    "UserId": "SecurityComplianceAlerts",
    "AlertId": "3d903b26-58e4-43bb-b557-1f583fd28a4d",
    "AlertLinks": [
        {
            "AlertLinkHref": ""
        }
    ],
    "AlertType": "System",
    "Category": "ThreatManagement",
    "Comments": "New alert",
    "Data": "{\"ts\":\"2023-09-19T06:05:05.0000000Z\",\"te\":\"2023-09-19T06:05:05.0000000Z\",\"tid\":\"b3b00feb-0b31-4458-8dc6-612e14e12878\",\"tdc\":\"1\",\"af\":\"0\",\"tht\":\"Phish, Malicious\",\"als\":\"Protection\",\"op\":\"Protection\",\"wsrt\":\"0001-01-01T00:00:00\",\"mdt\":\"u\",\"rid\":\"9b89e2c5-1a5b-4304-88e3-1d246e7da190\",\"cid\":\"38b8a3ae-4adc-46de-9c1a-469b5ed640a9\",\"ad\":\"This alert fires when message containing phish was delivered due to an ETR override. -V1.0.0.5\",\"lon\":\"Protection\",\"an\":\"Phish delivered due to an ETR override\",\"sev\":\"Informational\"}",
    "Name": "Phish delivered due to an ETR override",
    "PolicyId": "38b8a3ae-4adc-46de-9c1a-469b5ed640a9",
    "Severity": "Informational",
    "Source": "Office 365 Security & Compliance",
    "Status": "Active"
}
```

**Comment by gcl-sekoia** [comment]
Should we parse the Data blob when it's JSON? (Not sure if it always is, but likely).

**Comment by gcl-sekoia** [comment]
For reference, if it can be useful, here's the Elastic parser:
https://github.com/elastic/integrations/blob/main/packages/o365/data_stream/audit/elasticsearch/ingest_pipeline/default.yml#L463-L545

**Comment by gcl-sekoia** [comment]
I have added the test event, moved the parsing in a dedicated stage, and changed the field names a bit.
I think that we don't need to parse the Data blob for now. We'll see if it becomes necessary later.

**Comment by squioc** [comment]
My bad. We also worked on the related issue (see https://github.com/SEKOIA-IO/intake-formats/pull/757).
Can we close this PR?

**Pull request closed without merging**
