### PR TITLE
New legacy parser - Gatewatcher AIonIQ

### PR DESCRIPTION
**Pull request by clement-lyonnet**
Here is a new version of the legacy parser for Gatewatcher AionIQ.
New fields have been created and we are not able to generate the fields.yml file from the interface, so maybe you can add your version of the new fields.yml file ?

Thank you very much

### CODE REVIEW

**Comment by clement-lyonnet** [comment]
Hello, I have pushed the necessary changes. Feel free to tell if there is changes to apply, thanks

**Review by squioc — CHANGES_REQUESTED** [review]
Can you update the tests?
```
$ cd utils
$ poetry run test_formats.py --format aioniq --fix-expectations
```

It seems that `gatewatcher.smtp` is missing from the taxonomy (ie, fields.yml). Can you add it?

**Comment by squioc** [comment]
Can you update the tests recently added with the expected fields?
```
$ cd utils
$ poetry run test_formats.py --format aioniq --fix-expectations
```
Thank you.

**Comment by clement-lyonnet** [comment]
Hello, it seems that the failing test is the same issue that this one : https://github.com/peter-evans/create-or-update-comment/issues/188 or do I need to change the permissions somewhere ?

**Review by squioc — APPROVED** [review]
LGTM

**Pull request merged**
